kind: pipeline
name: live-stream-user-service

# NOTE: modify here to ensure number of migrations are correct
steps:
  - name: up-test
    image: debian
    environment:
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASS:
        from_secret: postgres_pass
      POSTGRES_HOST:
        from_secret: postgres_host
      POSTGRES_DB:
        from_secret: postgres_db
    commands:
      - apt-get update; apt-get install -y curl; apt-get install -y gnupg
      - curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
      - echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
      - apt-get update
      - apt-get install -y migrate
      - migrate -source file://migrations -database postgres://POSTGRES_USER:POSTGRES_PASS@POSTGRES_HOST:5432/POSTGRES_DB?sslmode=disable up 1
        # - migrate -source file://migrations -database postgres://POSTGRES_USER:POSTGRES_PASS@POSTGRES_HOST:5432/POSTGRES_DB?sslmode=disable up 1
        # - docker run -v migrations:/migrations migrate/migrate \
        #   -database postgres://POSTGRES_USER:POSTGRES_PASS@POSTGRES_HOST:5432/POSTGRES_DB?sslmode=disable \
        #   -path /migrations/ up
  # down
  # up