kind: pipeline
name: live-stream-user-service

# NOTE: modify here to ensure number of migrations are correct
steps:
  - name: up-test
    image: docker
    environment:
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASS:
        from_secret: postgres_pass
      POSTGRES_HOST:
        from_secret: postgres_host
      POSTGRES_DB:
        from_secret: postgres_db
    commands:
      - docker run -v migrations:/migrations migrate/migrate \
        -database postgres://POSTGRES_USER:POSTGRES_PASS@POSTGRES_HOST:5432/POSTGRES_DB?sslmode=disable \
        -path /migrations/ up
  # down
  # up