kind: pipeline
name: live-stream-user-service
environment:
  STEPS: 1

# NOTE: modify here to ensure number of migrations are correct
steps:
  - name: deploy
    image: golang
    environment:
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASS:
        from_secret: postgres_pass
      POSTGRES_HOST:
        from_secret: postgres_host
      POSTGRES_DB:
        from_secret: postgres_db
    commands:
      - go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
      - echo $STEPS
      - migrate -source file://migrations -database postgres://$POSTGRES_USER:$POSTGRES_PASS@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable up $STEPS
      - migrate -source file://migrations -database postgres://$POSTGRES_USER:$POSTGRES_PASS@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable down $STEPS
      - migrate -source file://migrations -database postgres://$POSTGRES_USER:$POSTGRES_PASS@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable up $STEPS
# TODO: promote steps
