kind: pipeline
name: live-stream-user-service

# NOTE: modify here to ensure number of migrations are correct
steps:
  - name: up-test
    image: migrate/migrate
    environment:
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASS:
        from_secret: postgres_pass
      POSTGRES_HOST:
        from_secret: postgres_host
      POSTGRES_DB:
        from_secret: postgres_db
    bash:
      script:
        - migrate -source file://migrations -database postgres://POSTGRES_USER:POSTGRES_PASS@POSTGRES_HOST:5432/POSTGRES_DB?sslmode=disable up
  # down
  # up