CREATE TABLE LIVE_STREAM_USERS (
    _ID VARCHAR(255) UNIQUE,
    STRIPE_CUSTOMER_ID VARCHAR(255),
    NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (_ID, EMAIL)
);

-- TODO: m:m roles tables