CREATE TABLE LIVE_STREAM_BILLING_EVENTS (
	_ID VARCHAR(255) UNIQUE,
	RELATED_UNIT_ID VARCHAR(255), -- generic foreign key
	USER_ID VARCHAR(255) REFERENCES LIVE_STREAM_USERS(_ID),
	PLAN_ID VARCHAR(255),
	INVOICE_ITEM_ID VARCHAR(255),
	PAYMENT_EVENT_ID VARCHAR(255),
	AMOUNT_BILLED DECIMAL,
	START_TIME TIMESTAMP,
	STOP_TIME TIMESTAMP,
	PRIMARY KEY (_ID)
)

-- TODO: update schema, make script to automate migrations
-- TODO: trigger to set start and end to current time if being set
